# 开发环境配置
#springdoc:
#  paths-to-match: /api/**
#  swagger-ui:
#    operations-sorter: alpha

spring:
  mail:
    host: imap.139.com
    username: dr.ysg@139.com
    password: f4973afe85ac75547300

#  rabbitmq:
#    addresses: localhost
#    username: admin
#    password: admin
#    virtual-host: /

  datasource:
    url: jdbc:mysql://localhost:3306/db_account?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 5409
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    jwt:
      key: 'ysg5409'
      expire: 72
      limit:
        base: 1
        upgrade: 1
        frequency: 300
#    filter:
#      order: -100
#  web:
#    verify:
#      mail-limit: 60
#    flow:
#      period: 3
#      limit: 50
#      block: 30
#    cors:
#      origin: '*'
#      credentials: false
#      methods: '*'